console_title_template = '{{ .Shell }} in {{ .PWD }}'
version = 3
shell_integration = true

[palette]
  base = '#1E1E2E'
  blue = '#89B4FA'
  crust = '#11111B'
  docker = 'p:sky'
  false = 'p:red'
  flamingo = '#F2CDCD'
  git = 'p:lavender'
  go = 'p:mauve'
  green = '#A6E3A1'
  haskell = 'p:mauve'
  julia = 'p:mauve'
  lavender = '#B4BEFE'
  lua = 'p:mauve'
  mantle = '#181825'
  maroon = '#EBA0AC'
  mauve = '#CBA6F7'
  os-bg = 'p:overlay1'
  os-fg = 'p:base'
  overlay0 = '#6C7086'
  overlay1 = '#7F849C'
  overlay2 = '#9399B2'
  path = 'p:yellow'
  peach = '#FAB387'
  pink = '#F5C2E7'
  python = 'p:mauve'
  red = '#F38BA8'
  root-bg = 'p:yellow'
  root-fg = 'p:base'
  rosewater = '#F5E0DC'
  rust = 'p:mauve'
  sapphire = '#74C7EC'
  sky = '#89DCEB'
  subtext0 = '#A6ADC8'
  subtext1 = '#BAC2DE'
  surface0 = '#313244'
  surface1 = '#45475A'
  surface2 = '#585B70'
  teal = '#94E2D5'
  text = '#CDD6F4'
  time = 'p:overlay1'
  true = 'p:green'
  yellow = '#F9E2AF'

[transient_prompt]
  template = '{{ now | date "15:04:05" }} {{ if gt .Code 0 }}<p:false>❯</>{{ else }}<p:true>❯</>{{ end }} '
  foreground = 'p:time'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' {{ .Icon }} '
    foreground = 'p:sapphire'
    background = 'p:surface2'
    type = 'os'
    style = 'diamond'
    foreground_templates = ['{{ if .Root }}p:root-fg{{ end }}']
    background_templates = ['{{ if .Root }}p:root-bg{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'
      windows = ''

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = 'p:path'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '..'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    template = '{{ .HEAD }} '
    foreground = 'p:git'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_stash_count = false
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    template = ' {{ .Context }} '
    foreground = 'p:docker'
    type = 'docker'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ .Full }}{{ end }} '
    foreground = 'p:go'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ .Full }}{{ end }} '
    foreground = 'p:haskell'
    type = 'haskell'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ .Full }}{{ end }} '
    foreground = 'p:julia'
    type = 'julia'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ .Full }}{{ end }} '
    foreground = 'p:lua'
    type = 'lua'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ if .Venv }}venv/{{ end }}{{ .Full }}{{ end }} '
    foreground = 'p:python'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_default = false
      display_mode = 'context'

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ .Full }}{{ end }} '
    foreground = 'p:rust'
    type = 'rust'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '󰔟 {{ .FormattedMs }} '
    foreground = 'p:true'
    type = 'executiontime'
    style = 'plain'
    foreground_templates = ['{{ if .Code }}p:false{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'austin'
      threshold = 500.0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯ '
    # template = ' '
    foreground = 'p:true'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}p:false{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
